function [matlabbatch] = job_ROI_mask_step01(inputROIfile,outputDir)
%Separate ROI mask into indiviual ROI masks


%-----------------------------------------------------------------------
% Job saved on 06-Oct-2016 15:51:55 by cfg_util (rev $Rev: 6460 $)
% spm SPM - SPM12 (6470)
%-----------------------------------------------------------------------
matlabbatch{1}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{1}.spm.util.imcalc.output = 'R_PRC.nii';
matlabbatch{1}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{1}.spm.util.imcalc.expression = 'i1==1';
matlabbatch{1}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{1}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{1}.spm.util.imcalc.options.mask = 0;
matlabbatch{1}.spm.util.imcalc.options.interp = 1;
matlabbatch{1}.spm.util.imcalc.options.dtype = 4;
matlabbatch{2}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{2}.spm.util.imcalc.output = 'R_ERC.nii';
matlabbatch{2}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{2}.spm.util.imcalc.expression = 'i1==2';
matlabbatch{2}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{2}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{2}.spm.util.imcalc.options.mask = 0;
matlabbatch{2}.spm.util.imcalc.options.interp = 1;
matlabbatch{2}.spm.util.imcalc.options.dtype = 4;
matlabbatch{3}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{3}.spm.util.imcalc.output = 'R_PHC.nii';
matlabbatch{3}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{3}.spm.util.imcalc.expression = 'i1==3';
matlabbatch{3}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{3}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{3}.spm.util.imcalc.options.mask = 0;
matlabbatch{3}.spm.util.imcalc.options.interp = 1;
matlabbatch{3}.spm.util.imcalc.options.dtype = 4;
matlabbatch{4}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{4}.spm.util.imcalc.output = 'R_Sub.nii';
matlabbatch{4}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{4}.spm.util.imcalc.expression = 'i1==4';
matlabbatch{4}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{4}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{4}.spm.util.imcalc.options.mask = 0;
matlabbatch{4}.spm.util.imcalc.options.interp = 1;
matlabbatch{4}.spm.util.imcalc.options.dtype = 4;
matlabbatch{5}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{5}.spm.util.imcalc.output = 'R_CADG_ant.nii';
matlabbatch{5}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{5}.spm.util.imcalc.expression = 'i1==5';
matlabbatch{5}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{5}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{5}.spm.util.imcalc.options.mask = 0;
matlabbatch{5}.spm.util.imcalc.options.interp = 1;
matlabbatch{5}.spm.util.imcalc.options.dtype = 4;
matlabbatch{6}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{6}.spm.util.imcalc.output = 'R_CA1.nii';
matlabbatch{6}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{6}.spm.util.imcalc.expression = 'i1==6';
matlabbatch{6}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{6}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{6}.spm.util.imcalc.options.mask = 0;
matlabbatch{6}.spm.util.imcalc.options.interp = 1;
matlabbatch{6}.spm.util.imcalc.options.dtype = 4;
matlabbatch{7}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{7}.spm.util.imcalc.output = 'R_CA3DG.nii';
matlabbatch{7}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{7}.spm.util.imcalc.expression = 'i1==7';
matlabbatch{7}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{7}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{7}.spm.util.imcalc.options.mask = 0;
matlabbatch{7}.spm.util.imcalc.options.interp = 1;
matlabbatch{7}.spm.util.imcalc.options.dtype = 4;
matlabbatch{8}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{8}.spm.util.imcalc.output = 'R_CADG_post.nii';
matlabbatch{8}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{8}.spm.util.imcalc.expression = 'i1==8';
matlabbatch{8}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{8}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{8}.spm.util.imcalc.options.mask = 0;
matlabbatch{8}.spm.util.imcalc.options.interp = 1;
matlabbatch{8}.spm.util.imcalc.options.dtype = 4;
matlabbatch{9}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{9}.spm.util.imcalc.output = 'L_PRC.nii';
matlabbatch{9}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{9}.spm.util.imcalc.expression = 'i1==9';
matlabbatch{9}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{9}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{9}.spm.util.imcalc.options.mask = 0;
matlabbatch{9}.spm.util.imcalc.options.interp = 1;
matlabbatch{9}.spm.util.imcalc.options.dtype = 4;
matlabbatch{10}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{10}.spm.util.imcalc.output = 'L_ERC.nii';
matlabbatch{10}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{10}.spm.util.imcalc.expression = 'i1==10';
matlabbatch{10}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{10}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{10}.spm.util.imcalc.options.mask = 0;
matlabbatch{10}.spm.util.imcalc.options.interp = 1;
matlabbatch{10}.spm.util.imcalc.options.dtype = 4;
matlabbatch{11}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{11}.spm.util.imcalc.output = 'L_PHC.nii';
matlabbatch{11}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{11}.spm.util.imcalc.expression = 'i1==11';
matlabbatch{11}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{11}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{11}.spm.util.imcalc.options.mask = 0;
matlabbatch{11}.spm.util.imcalc.options.interp = 1;
matlabbatch{11}.spm.util.imcalc.options.dtype = 4;
matlabbatch{12}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{12}.spm.util.imcalc.output = 'L_Sub.nii';
matlabbatch{12}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{12}.spm.util.imcalc.expression = 'i1==12';
matlabbatch{12}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{12}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{12}.spm.util.imcalc.options.mask = 0;
matlabbatch{12}.spm.util.imcalc.options.interp = 1;
matlabbatch{12}.spm.util.imcalc.options.dtype = 4;
matlabbatch{13}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{13}.spm.util.imcalc.output = 'L_CADG_ant.nii';
matlabbatch{13}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{13}.spm.util.imcalc.expression = 'i1==13';
matlabbatch{13}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{13}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{13}.spm.util.imcalc.options.mask = 0;
matlabbatch{13}.spm.util.imcalc.options.interp = 1;
matlabbatch{13}.spm.util.imcalc.options.dtype = 4;
matlabbatch{14}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{14}.spm.util.imcalc.output = 'L_CA1.nii';
matlabbatch{14}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{14}.spm.util.imcalc.expression = 'i1==14';
matlabbatch{14}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{14}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{14}.spm.util.imcalc.options.mask = 0;
matlabbatch{14}.spm.util.imcalc.options.interp = 1;
matlabbatch{14}.spm.util.imcalc.options.dtype = 4;
matlabbatch{15}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{15}.spm.util.imcalc.output = 'L_CA3DG.nii';
matlabbatch{15}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{15}.spm.util.imcalc.expression = 'i1==15';
matlabbatch{15}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{15}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{15}.spm.util.imcalc.options.mask = 0;
matlabbatch{15}.spm.util.imcalc.options.interp = 1;
matlabbatch{15}.spm.util.imcalc.options.dtype = 4;
matlabbatch{16}.spm.util.imcalc.input = {inputROIfile};
matlabbatch{16}.spm.util.imcalc.output = 'L_CADG_post.nii';
matlabbatch{16}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{16}.spm.util.imcalc.expression = 'i1==16';
matlabbatch{16}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{16}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{16}.spm.util.imcalc.options.mask = 0;
matlabbatch{16}.spm.util.imcalc.options.interp = 1;
matlabbatch{16}.spm.util.imcalc.options.dtype = 4;
matlabbatch{17}.spm.util.imcalc.input(1) = cfg_dep('Image Calculator: ImCalc Computed Image: R_Sub.nii', substruct('.','val', '{}',{4}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{17}.spm.util.imcalc.input(2) = cfg_dep('Image Calculator: ImCalc Computed Image: R_CADG_ant.nii', substruct('.','val', '{}',{5}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{17}.spm.util.imcalc.input(3) = cfg_dep('Image Calculator: ImCalc Computed Image: R_CA1.nii', substruct('.','val', '{}',{6}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{17}.spm.util.imcalc.input(4) = cfg_dep('Image Calculator: ImCalc Computed Image: R_CA3DG.nii', substruct('.','val', '{}',{7}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{17}.spm.util.imcalc.input(5) = cfg_dep('Image Calculator: ImCalc Computed Image: R_CADG_post.nii', substruct('.','val', '{}',{8}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{17}.spm.util.imcalc.output = 'R_Hipp.nii';
matlabbatch{17}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{17}.spm.util.imcalc.expression = 'i1+i2+i3+i4+i5';
matlabbatch{17}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{17}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{17}.spm.util.imcalc.options.mask = 0;
matlabbatch{17}.spm.util.imcalc.options.interp = 1;
matlabbatch{17}.spm.util.imcalc.options.dtype = 4;
matlabbatch{18}.spm.util.imcalc.input(1) = cfg_dep('Image Calculator: ImCalc Computed Image: L_Sub.nii', substruct('.','val', '{}',{12}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{18}.spm.util.imcalc.input(2) = cfg_dep('Image Calculator: ImCalc Computed Image: L_CADG_ant.nii', substruct('.','val', '{}',{13}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{18}.spm.util.imcalc.input(3) = cfg_dep('Image Calculator: ImCalc Computed Image: L_CA1.nii', substruct('.','val', '{}',{14}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{18}.spm.util.imcalc.input(4) = cfg_dep('Image Calculator: ImCalc Computed Image: L_CA3DG.nii', substruct('.','val', '{}',{15}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{18}.spm.util.imcalc.input(5) = cfg_dep('Image Calculator: ImCalc Computed Image: L_CADG_post.nii', substruct('.','val', '{}',{16}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{18}.spm.util.imcalc.output = 'L_Hipp.nii';
matlabbatch{18}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{18}.spm.util.imcalc.expression = 'i1+i2+i3+i4+i5';
matlabbatch{18}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{18}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{18}.spm.util.imcalc.options.mask = 0;
matlabbatch{18}.spm.util.imcalc.options.interp = 1;
matlabbatch{18}.spm.util.imcalc.options.dtype = 4;
matlabbatch{19}.spm.util.imcalc.input(1) = cfg_dep('Image Calculator: ImCalc Computed Image: R_PRC.nii', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{19}.spm.util.imcalc.input(2) = cfg_dep('Image Calculator: ImCalc Computed Image: L_PRC.nii', substruct('.','val', '{}',{9}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{19}.spm.util.imcalc.output = 'Bi_PRC.nii';
matlabbatch{19}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{19}.spm.util.imcalc.expression = 'i1+i2';
matlabbatch{19}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{19}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{19}.spm.util.imcalc.options.mask = 0;
matlabbatch{19}.spm.util.imcalc.options.interp = 1;
matlabbatch{19}.spm.util.imcalc.options.dtype = 4;
matlabbatch{20}.spm.util.imcalc.input(1) = cfg_dep('Image Calculator: ImCalc Computed Image: R_ERC.nii', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{20}.spm.util.imcalc.input(2) = cfg_dep('Image Calculator: ImCalc Computed Image: L_ERC.nii', substruct('.','val', '{}',{10}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{20}.spm.util.imcalc.output = 'Bi_ERC.nii';
matlabbatch{20}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{20}.spm.util.imcalc.expression = 'i1+i2';
matlabbatch{20}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{20}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{20}.spm.util.imcalc.options.mask = 0;
matlabbatch{20}.spm.util.imcalc.options.interp = 1;
matlabbatch{20}.spm.util.imcalc.options.dtype = 4;
matlabbatch{21}.spm.util.imcalc.input(1) = cfg_dep('Image Calculator: ImCalc Computed Image: R_PHC.nii', substruct('.','val', '{}',{3}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{21}.spm.util.imcalc.input(2) = cfg_dep('Image Calculator: ImCalc Computed Image: L_PHC.nii', substruct('.','val', '{}',{11}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{21}.spm.util.imcalc.output = 'Bi_PHC.nii';
matlabbatch{21}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{21}.spm.util.imcalc.expression = 'i1+i2';
matlabbatch{21}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{21}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{21}.spm.util.imcalc.options.mask = 0;
matlabbatch{21}.spm.util.imcalc.options.interp = 1;
matlabbatch{21}.spm.util.imcalc.options.dtype = 4;
matlabbatch{22}.spm.util.imcalc.input(1) = cfg_dep('Image Calculator: ImCalc Computed Image: R_Hipp.nii', substruct('.','val', '{}',{17}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{22}.spm.util.imcalc.input(2) = cfg_dep('Image Calculator: ImCalc Computed Image: L_Hipp.nii', substruct('.','val', '{}',{18}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{22}.spm.util.imcalc.output = 'Bi_Hipp.nii';
matlabbatch{22}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{22}.spm.util.imcalc.expression = 'i1+i2';
matlabbatch{22}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{22}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{22}.spm.util.imcalc.options.mask = 0;
matlabbatch{22}.spm.util.imcalc.options.interp = 1;
matlabbatch{22}.spm.util.imcalc.options.dtype = 4;
matlabbatch{23}.spm.util.imcalc.input(1) = cfg_dep('Image Calculator: ImCalc Computed Image: R_Sub.nii', substruct('.','val', '{}',{4}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{23}.spm.util.imcalc.input(2) = cfg_dep('Image Calculator: ImCalc Computed Image: L_Sub.nii', substruct('.','val', '{}',{12}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{23}.spm.util.imcalc.output = 'Bi_Sub.nii';
matlabbatch{23}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{23}.spm.util.imcalc.expression = 'i1+i2';
matlabbatch{23}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{23}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{23}.spm.util.imcalc.options.mask = 0;
matlabbatch{23}.spm.util.imcalc.options.interp = 1;
matlabbatch{23}.spm.util.imcalc.options.dtype = 4;
matlabbatch{24}.spm.util.imcalc.input(1) = cfg_dep('Image Calculator: ImCalc Computed Image: R_CADG_ant.nii', substruct('.','val', '{}',{5}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{24}.spm.util.imcalc.input(2) = cfg_dep('Image Calculator: ImCalc Computed Image: L_CADG_ant.nii', substruct('.','val', '{}',{13}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{24}.spm.util.imcalc.output = 'Bi_CA3DG_ant.nii';
matlabbatch{24}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{24}.spm.util.imcalc.expression = 'i1+i2';
matlabbatch{24}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{24}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{24}.spm.util.imcalc.options.mask = 0;
matlabbatch{24}.spm.util.imcalc.options.interp = 1;
matlabbatch{24}.spm.util.imcalc.options.dtype = 4;
matlabbatch{25}.spm.util.imcalc.input(1) = cfg_dep('Image Calculator: ImCalc Computed Image: R_CA1.nii', substruct('.','val', '{}',{6}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{25}.spm.util.imcalc.input(2) = cfg_dep('Image Calculator: ImCalc Computed Image: L_CA1.nii', substruct('.','val', '{}',{14}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{25}.spm.util.imcalc.output = 'Bi_CA1.nii';
matlabbatch{25}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{25}.spm.util.imcalc.expression = 'i1+i2';
matlabbatch{25}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{25}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{25}.spm.util.imcalc.options.mask = 0;
matlabbatch{25}.spm.util.imcalc.options.interp = 1;
matlabbatch{25}.spm.util.imcalc.options.dtype = 4;
matlabbatch{26}.spm.util.imcalc.input(1) = cfg_dep('Image Calculator: ImCalc Computed Image: R_CA3DG.nii', substruct('.','val', '{}',{7}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{26}.spm.util.imcalc.input(2) = cfg_dep('Image Calculator: ImCalc Computed Image: L_CA3DG.nii', substruct('.','val', '{}',{15}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{26}.spm.util.imcalc.output = 'Bi_CA3DG.nii';
matlabbatch{26}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{26}.spm.util.imcalc.expression = 'i1+i2';
matlabbatch{26}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{26}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{26}.spm.util.imcalc.options.mask = 0;
matlabbatch{26}.spm.util.imcalc.options.interp = 1;
matlabbatch{26}.spm.util.imcalc.options.dtype = 4;
matlabbatch{27}.spm.util.imcalc.input(1) = cfg_dep('Image Calculator: ImCalc Computed Image: R_CADG_post.nii', substruct('.','val', '{}',{8}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{27}.spm.util.imcalc.input(2) = cfg_dep('Image Calculator: ImCalc Computed Image: L_CADG_post.nii', substruct('.','val', '{}',{16}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','files'));
matlabbatch{27}.spm.util.imcalc.output = 'Bi_CA3DG_post.nii';
matlabbatch{27}.spm.util.imcalc.outdir = {outputDir};
matlabbatch{27}.spm.util.imcalc.expression = 'i1+i2';
matlabbatch{27}.spm.util.imcalc.var = struct('name', {}, 'value', {});
matlabbatch{27}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{27}.spm.util.imcalc.options.mask = 0;
matlabbatch{27}.spm.util.imcalc.options.interp = 1;
matlabbatch{27}.spm.util.imcalc.options.dtype = 4;


spm('defaults','fmri');
spm_jobman('initcfg');
spm_jobman('run',matlabbatch);
end

